version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: posadmin
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: