name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable && pnpm install
      - run: pnpm --filter=@SpaceTrev/ui run build-storybook

      - name: Deploy to /storybook folder on gh-pages
        run: |
          git fetch
          git switch gh-pages || git checkout -b gh-pages
          mkdir -p storybook
          cp -r ./packages/ui/storybook-static/* ./storybook/
          git add storybook
          git commit -m "Update Storybook in /storybook"
          git push origin gh-pages