name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable && pnpm install

      - name: Create Release Pull Request or Publish to GitHub Releases
        uses: changesets/action@v1
        with:
          publish: pnpm publish -r --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}